<?php
/**
 * Created by PhpStorm.
 * User: breic
 * Date: 11/27/2018
 * Time: 10:38 PM
 */

namespace RWC\Shutterfly;

/**
 * A request for a label for a single shipment.
 */
class ShipmentRequest
{
    /**
     * A unique shipment identifier generated by fulfiller; this is the
     * identifier typically fulfillers send in the shipment acknowledgement
     * (shipment per label/package) that shutterfly receives today. if the
     * ShipmentRequest contains a list of PackageRequest object for a
     * multi-package shipment, this number shuold match one of the contained
     * package request numbers.
     * 
     * @var string
     */
    protected $shipmentNo;

    /**
     * Proposed shipment date, the date that the shipment is expected to
     * leave the fulfiller's site. The service would determine actual carrier
     * "pickup" date from this proposed "ship date." Formatted per section 10.1.
     * 
     * @var DateTime
     */
    protected $shipDate;

    /**
     * Proposed shipping carrier name. The value should be one of the carrier
     * identifiers that is listed in section 10.2. This is used in version 1
     * as the algorithm starting point, if provided for version 2, will force
     * the label to be created using this carrier.
     * 
     * @var string|null
     */
    protected $expectedCarrier;

    /**
     * Proposed ship method for carrier. The value should be one of the
     * ship method identifiers that is listed in section 10.3 for the
     * expected carrier. This is used for version 1 as the algorithm
     * starting point, if provided for version 2, will force the label
     * to be created using the carrier method.
     * 
     * @var string|null
     */
    protected $expectedShipMethod;

    /**
     * Shipment "from" postal code -- fulfiller's postal code, as agreed
     * with Shutterfly team.
     * 
     * @var string
     */
    protected $sourceZip;

    /**
     * Measure weight of the shipment in ounces.
     * 
     * @var float|null
     */
    protected $weight;

    /**
     * The Shutterfly packaging part number(s) for this package.
     * Can be repeated for packages with multiple packaging.
     * 
     * @var string|null
     */
    protected $packagingPartNo;

    /**
     * Optional dimension for generic non-Shutterfly packages in inches.
     * 
     * @var float|null
     */
    protected $height;

    /**
     * Optional dimension for generic non-Shutterfly packages in inches.
     * 
     * @var float|null
     */
    protected $length;

    /**
     * Optional dimension for generic non-Shutterfly packages in inches.
     * 
     * @var float|null
     */
    protected $width;

    /**
     * List of shipment items included in this shipment. See section 4.1.3.
     * 
     * @var ShpimentItem[]
     */
    protected $items;

    /**
     * List of PackageRequest definitions containing all packages in this
     * shipment. This attribute is only valid for shipment requests with
     * printLabel = true.
     * 
     * @var PackageRequest|null
     */
    protected $packages;

    /**
     * Data to be included on the label, such as fulfiller internal tracking
     * number.
     * 
     * @var string|null
     */
    protected $senderReference1;

    /**
     * Optional ShipAddressType element used in special cases when order
     * address cannot be modified, but shipment address must be changed.
     * 
     * @var Address|null
     */
    protected $address;

    /**
     * Customize element, see section 9.2.
     * 
     * @var Customize|null
     */
    protected $customize;
}